runtime: python311
entrypoint: gunicorn -b :$PORT main:app
instance_class: F2
automatic_scaling:
  max_instances: 1
env_variables:
  GOOGLE_PROJECT_ID: "parabolic-might-310418"
  GOOGLE_CLIENT_ID: "699250757113-89tgjnop0e20gvjks5oqjqlvb2g77dst.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "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"
  DOC_ID_DADOS_INQUILINOS: "1UzHWKA-qZTEfPDXs1l4o7FUp3BuI-MZcU3aEqYYJCbo"