steps:
    - name: 'gcr.io/cloud-builders/gcloud'
      args: ['app', 'deploy']
# Post-deployment script execution
    - name: 'python'
      script: |
        #!/usr/bin/env python
        print('hello from python')
options:
    logging: CLOUD_LOGGING_ONLY
